export const GOOGLE_API_KEY = 'AIzaSyCUGxDFUFYJIpUnQLTkVi2r1hCZ2Ajs2J8';
export const GEOLOCATION_API = 'AIzaSyBZ4zHguSsWf8ZcGe0BY-4eQlKRFIx9PSM'
// export const GOOGLE_API_KEY = 'AIzaSyB3YB8Sd-DiKYY-9uN9Sg1qMFkTa95TA7Q';
